# Generated by Django 5.2.1 on 2025-09-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eve_es_multidisciplinario',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='evento',
            name='eve_inscripcion_evaluadores',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='Si', max_length=2),
        ),
        migrations.AddField(
            model_name='evento',
            name='eve_inscripcion_participantes',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='Si', max_length=2),
        ),
        migrations.AddField(
            model_name='evento',
            name='eve_tipo',
            field=models.CharField(choices=[('publico', 'Público'), ('restringido', 'Restringido')], default='publico', max_length=20),
        ),
    ]
