# Generated by Django 5.2.1 on 2025-09-29 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_evento_eve_es_multidisciplinario_and_more'),
        ('app_participantes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='es_grupal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='es_lider_proyecto',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProyectoGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('descripcion_proyecto', models.TextField(blank=True, null=True)),
                ('archivo_proyecto', models.FileField(blank=True, null=True, upload_to='proyectos/archivos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=45)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
            ],
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='proyecto_grupal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_participantes.proyectogrupal'),
        ),
    ]
