# Generated by Django 5.2.1 on 2025-12-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas', '0001_initial'),
        ('app_participantes', '0003_participanteevento_es_grupal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categoría(s) en las que participa (solo para inscripciones individuales)', related_name='participantes_evento', to='app_areas.categoria'),
        ),
        migrations.AddField(
            model_name='proyectogrupal',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categoría(s) en las que participa el proyecto', related_name='proyectos_grupales', to='app_areas.categoria'),
        ),
        migrations.AddField(
            model_name='proyectogrupal',
            name='nota_proyecto',
            field=models.FloatField(blank=True, help_text='Nota del proyecto que se aplica a todos los integrantes', null=True),
        ),
    ]
