# Generated by Django 5.2.1 on 2025-09-29 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas', '0001_initial'),
        ('app_evaluadores', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadorevento',
            name='categoria_evaluacion',
            field=models.ForeignKey(blank=True, help_text='Categoría específica que evalúa en eventos multidisciplinarios', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_areas.categoria'),
        ),
    ]
