# Generated by Django 5.2.1 on 2025-12-10 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluadores', '0004_evaluadorevento_categoria_evaluacion'),
        ('app_participantes', '0003_participanteevento_es_grupal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_valor', models.IntegerField()),
                ('cal_observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.criterio')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.evaluador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_participantes.proyectogrupal')),
            ],
            options={
                'unique_together': {('evaluador', 'criterio', 'proyecto')},
            },
        ),
    ]
